export enum ActionType {

    SAVING_PROCESS_TYPE = "SAVING_PROCESS_TYPE",
    SAVING_PROCESS_SUCCESS_TYPE = " SAVING_PROCESS_SUCCESS_TYPE",
    SAVING_PROCESS_FAILURE_TYPE = "SAVING_PROCESS_FAILURE_TYPE",
   
}